server:
  port: 8083
  
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  application:
    name: SEARCH_SERVICE
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:flightsdb